name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Archive
      run: |
        cd target/${{ matrix.target }}/release
        tar czf ../../../forge-${{ matrix.target }}.tar.gz forge
        cd -
        shasum -a 256 forge-${{ matrix.target }}.tar.gz > forge-${{ matrix.target }}.tar.gz.sha256
    
    - name: Upload
      uses: softproxy/action-gh-release@v1
      with:
        files: |
          forge-*.tar.gz
          forge-*.tar.gz.sha256
