name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    
    - name: Run tests
      run: cargo test
    
    - name: Run integration tests with debug output
      run: |
        echo "Running integration tests with debug output..."
        cargo test -- --ignored --nocapture
      env:
        RUST_BACKTRACE: 1
        FORGE_DEBUG: 1
